// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of AboutUs ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class AboutUsViewModel : BindableBase, IAboutUsViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutUsViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public AboutUsViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechAboutUsStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechAboutUsStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechAboutUsStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechAboutUsStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechAboutUsStaticControlCommand
        {
            get { return _textToSpeechAboutUsStaticControlCommand = _textToSpeechAboutUsStaticControlCommand ?? new DelegateCommand(TextToSpeechAboutUsStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareAboutUsStaticControlCommand command.
        /// </summary>
        public  void ShareAboutUsStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareAboutUsStaticControlCommand;

        /// <summary>
        /// Gets the ShareAboutUsStaticControlCommand command.
        /// </summary>
        public ICommand ShareAboutUsStaticControlCommand
        {
            get { return _shareAboutUsStaticControlCommand = _shareAboutUsStaticControlCommand ?? new DelegateCommand(ShareAboutUsStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartAboutUsStaticControlCommand command.
        /// </summary>
        public  void PinToStartAboutUsStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IAboutUsViewModel), CreateTileInfoAboutUsStaticControl());
        }
		

        private ICommand _pinToStartAboutUsStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartAboutUsStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartAboutUsStaticControlCommand
        {
            get { return _pinToStartAboutUsStaticControlCommand = _pinToStartAboutUsStaticControlCommand ?? new DelegateCommand(PinToStartAboutUsStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceAboutUsStaticControlCommand command.
        /// </summary>
        public  void GoToSourceAboutUsStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceAboutUsStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceAboutUsStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceAboutUsStaticControlCommand
        {
            get { return _goToSourceAboutUsStaticControlCommand = _goToSourceAboutUsStaticControlCommand ?? new DelegateCommand(GoToSourceAboutUsStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the AboutUsStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoAboutUsStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = @"http://appstudiodata.blob.core.windows.net/apps/30219/4d18ab18-5d4a-465d-a7db-37d48f59438f/res/Item-298e8a09-14ad-451b-b4f1-5526d37c4910.png",
                BackBackgroundImagePath = @"http://appstudiodata.blob.core.windows.net/apps/30219/4d18ab18-5d4a-465d-a7db-37d48f59438f/res/Item-298e8a09-14ad-451b-b4f1-5526d37c4910.png",
                LogoPath = "Logo-4ef38213-beeb-4b1f-9ea1-5a30d80ef3d6.png"
            };
            return tileInfo;
        }
    }
}
