// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// AboutUs ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IAboutUsViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechAboutUsStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechAboutUsStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAboutUsStaticControlCommand command.
        /// </summary>
		ICommand ShareAboutUsStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAboutUsStaticControlCommand command.
        /// </summary>
		ICommand PinToStartAboutUsStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceAboutUsStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceAboutUsStaticControlCommand { get; }

	}
}
