// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// LatestPosts_News ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ILatestPosts_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the LatestPosts_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<RssSearchResult> LatestPosts_NewsListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedLatestPosts_NewsListControlCollection property.
        /// </summary>
		RssSearchResult SelectedLatestPosts_NewsListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedMenuSection_MenuMenuControl property.
        /// </summary>
		MenuItemData SelectedMenuSection_MenuMenuControl { get; set; }

        
        /// <summary>
        /// Gets the RefreshLatestPosts_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshLatestPosts_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

	}
}
